/*
 * Appcelerator Titanium Mobile
 * Copyright (c) 2011-2016 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
var should = require('./should'),
	assert = require('./utilities/assertions');

describe('Titanium.UI', function () {

	// TODO Some of these are limited to specific platforms, we should mark them as such!
	var constantNumbers = [
		'ANIMATION_CURVE_EASE_IN', 'ANIMATION_CURVE_EASE_IN_OUT', 'ANIMATION_CURVE_EASE_OUT', 'ANIMATION_CURVE_LINEAR',
		'ATTRIBUTE_BACKGROUND_COLOR', 'ATTRIBUTE_BASELINE_OFFSET', 'ATTRIBUTE_EXPANSION', 'ATTRIBUTE_FONT', 'ATTRIBUTE_FOREGROUND_COLOR', 'ATTRIBUTE_KERN', 'ATTRIBUTE_LETTERPRESS_STYLE', 'ATTRIBUTE_LIGATURE', 'ATTRIBUTE_LINE_BREAK', 'ATTRIBUTE_LINE_BREAK_BY_CHAR_WRAPPING', 'ATTRIBUTE_LINE_BREAK_BY_CLIPPING', 'ATTRIBUTE_LINE_BREAK_BY_TRUNCATING_HEAD', 'ATTRIBUTE_LINE_BREAK_BY_TRUNCATING_MIDDLE', 'ATTRIBUTE_LINE_BREAK_BY_TRUNCATING_TAIL', 'ATTRIBUTE_LINE_BREAK_BY_WORD_WRAPPING', 'ATTRIBUTE_LINK', 'ATTRIBUTE_OBLIQUENESS', 'ATTRIBUTE_SHADOW', 'ATTRIBUTE_STRIKETHROUGH_COLOR', 'ATTRIBUTE_STRIKETHROUGH_STYLE', 'ATTRIBUTE_STROKE_COLOR', 'ATTRIBUTE_STROKE_WIDTH', 'ATTRIBUTE_TEXT_EFFECT', 'ATTRIBUTE_UNDERLINES_STYLE', 'ATTRIBUTE_UNDERLINE_BY_WORD', 'ATTRIBUTE_UNDERLINE_COLOR', 'ATTRIBUTE_UNDERLINE_PATTERN_DASH', 'ATTRIBUTE_UNDERLINE_PATTERN_DASH_DOT', 'ATTRIBUTE_UNDERLINE_PATTERN_DASH_DOT_DOT', 'ATTRIBUTE_UNDERLINE_PATTERN_DOT', 'ATTRIBUTE_UNDERLINE_PATTERN_SOLID', 'ATTRIBUTE_UNDERLINE_STYLE_DOUBLE', 'ATTRIBUTE_UNDERLINE_STYLE_NONE', 'ATTRIBUTE_UNDERLINE_STYLE_SINGLE', 'ATTRIBUTE_UNDERLINE_STYLE_THICK', 'ATTRIBUTE_WRITING_DIRECTION', 'ATTRIBUTE_WRITING_DIRECTION_EMBEDDING', 'ATTRIBUTE_WRITING_DIRECTION_LEFT_TO_RIGHT', 'ATTRIBUTE_WRITING_DIRECTION_NATURAL', 'ATTRIBUTE_WRITING_DIRECTION_OVERRIDE', 'ATTRIBUTE_WRITING_DIRECTION_RIGHT_TO_LEFT',
		'AUTOLINK_ALL', 'AUTOLINK_CALENDAR', 'AUTOLINK_EMAIL_ADDRESSES', 'AUTOLINK_MAP_ADDRESSES', 'AUTOLINK_NONE', 'AUTOLINK_PHONE_NUMBERS', 'AUTOLINK_URLS',
		'EXTEND_EDGE_ALL', 'EXTEND_EDGE_BOTTOM', 'EXTEND_EDGE_LEFT', 'EXTEND_EDGE_NONE', 'EXTEND_EDGE_RIGHT', 'EXTEND_EDGE_TOP',
		'FACE_DOWN', 'FACE_UP',
		'INPUT_BORDERSTYLE_BEZEL', 'INPUT_BORDERSTYLE_LINE', 'INPUT_BORDERSTYLE_NONE', 'INPUT_BORDERSTYLE_ROUNDED',
		'INPUT_BUTTONMODE_ALWAYS', 'INPUT_BUTTONMODE_NEVER', 'INPUT_BUTTONMODE_ONBLUR', 'INPUT_BUTTONMODE_ONFOCUS',
		'INPUT_TYPE_CLASS_NUMBER', 'INPUT_TYPE_CLASS_TEXT',
		'KEYBOARD_APPEARANCE_DARK', 'KEYBOARD_APPEARANCE_DEFAULT', 'KEYBOARD_APPEARANCE_LIGHT',
		'KEYBOARD_TYPE_ASCII', 'KEYBOARD_TYPE_DECIMAL_PAD', 'KEYBOARD_TYPE_DEFAULT', 'KEYBOARD_TYPE_EMAIL', 'KEYBOARD_TYPE_NAMEPHONE_PAD', 'KEYBOARD_TYPE_NUMBERS_PUNCTUATION', 'KEYBOARD_TYPE_NUMBER_PAD', 'KEYBOARD_TYPE_PHONE_PAD', 'KEYBOARD_TYPE_TWITTER', 'KEYBOARD_TYPE_URL', 'KEYBOARD_TYPE_WEBSEARCH',
		'LANDSCAPE_LEFT', 'LANDSCAPE_RIGHT',
		'LIST_ACCESSORY_TYPE_CHECKMARK', 'LIST_ACCESSORY_TYPE_DETAIL', 'LIST_ACCESSORY_TYPE_DISCLOSURE', 'LIST_ACCESSORY_TYPE_NONE',
		'LIST_ITEM_TEMPLATE_CONTACTS', 'LIST_ITEM_TEMPLATE_DEFAULT', 'LIST_ITEM_TEMPLATE_SETTINGS', 'LIST_ITEM_TEMPLATE_SUBTITLE',
		'NOTIFICATION_DURATION_LONG', 'NOTIFICATION_DURATION_SHORT',
		'PICKER_TYPE_COUNT_DOWN_TIMER', 'PICKER_TYPE_DATE', 'PICKER_TYPE_DATE_AND_TIME', 'PICKER_TYPE_PLAIN', 'PICKER_TYPE_TIME',
		'PORTRAIT',
		'RETURNKEY_CONTINUE', 'RETURNKEY_DEFAULT', 'RETURNKEY_DONE', 'RETURNKEY_EMERGENCY_CALL', 'RETURNKEY_GO', 'RETURNKEY_GOOGLE', 'RETURNKEY_JOIN', 'RETURNKEY_NEXT', 'RETURNKEY_ROUTE', 'RETURNKEY_SEARCH', 'RETURNKEY_SEND', 'RETURNKEY_YAHOO',
		'TABLE_VIEW_SEPARATOR_STYLE_NONE', 'TABLE_VIEW_SEPARATOR_STYLE_SINGLE_LINE',
		'TEXT_AUTOCAPITALIZATION_ALL', 'TEXT_AUTOCAPITALIZATION_NONE', 'TEXT_AUTOCAPITALIZATION_SENTENCES', 'TEXT_AUTOCAPITALIZATION_WORDS',
		'TEXT_ELLIPSIZE_TRUNCATE_END', 'TEXT_ELLIPSIZE_TRUNCATE_MARQUEE', 'TEXT_ELLIPSIZE_TRUNCATE_MIDDLE', 'TEXT_ELLIPSIZE_TRUNCATE_START',
		'UNKNOWN',
		'UPSIDE_PORTRAIT',
		'URL_ERROR_AUTHENTICATION', 'URL_ERROR_BAD_URL', 'URL_ERROR_CONNECT', 'URL_ERROR_FILE', 'URL_ERROR_FILE_NOT_FOUND', 'URL_ERROR_HOST_LOOKUP', 'URL_ERROR_REDIRECT_LOOP', 'URL_ERROR_SSL_FAILED', 'URL_ERROR_TIMEOUT', 'URL_ERROR_UNKNOWN', 'URL_ERROR_UNSUPPORTED_SCHEME'
	];
	var constantStrings = [
		'FILL', 'INHERIT', 'SIZE',
		'UNIT_CM', 'UNIT_DIP', 'UNIT_IN', 'UNIT_MM', 'UNIT_PX'
	];
	var constantsVary = [
		'TEXT_ALIGNMENT_CENTER', 'TEXT_ALIGNMENT_LEFT', 'TEXT_ALIGNMENT_RIGHT',
		// FIXME iOS only!
		'TEXT_STYLE_BODY', 'TEXT_STYLE_CAPTION1', 'TEXT_STYLE_CAPTION2', 'TEXT_STYLE_FOOTNOTE', 'TEXT_STYLE_HEADLINE', 'TEXT_STYLE_SUBHEADLINE',
		'TEXT_VERTICAL_ALIGNMENT_BOTTOM', 'TEXT_VERTICAL_ALIGNMENT_CENTER', 'TEXT_VERTICAL_ALIGNMENT_TOP'
	];

	// verify our constant Numbers
	for (var i = 0; i < constantNumbers.length; i++) {
		it(constantNumbers[i], function (finish) {
			should(Ti.UI[constantNumbers[i]]).be.a.readOnlyNumber;
			finish();
		});
	}

	// Verify our constant Strings
	for (var i = 0; i < constantStrings.length; i++) {
		it(constantStrings[i], function (finish) {
			should(Ti.UI[constantStrings[i]]).be.a.readOnlyString;
			finish();
		});
	}

	// Verify our constants that may be String or Number depending on platform.
	for (var i = 0; i < constantsVary.length; i++) {
		it(constantsVary[i], function (finish) {
			if (utilities.isAndroid()) {
				should(Ti.UI[constantsVary[i]]).be.a.readOnlyString;
			} else {
				should(Ti.UI[constantsVary[i]]).be.a.readOnlyNumber;
			}
			finish();
		});
	}
});
